HEALTH_POT = "hpot"
CLAW_SHARPENING = "cs"
GASOLINE = "gas"
COPPER_PLATING = "wax"
BOOK_OF_TRICKS = "tricks"
POTION_OF_STRONGER_WINGS = "wingpot"
CLAW_HONING = "ch"
ROCKET_FUEL = "rf"
IRON_PLATING = "iron"
BOOK_OF_MEGATRICKS = "mtrix"
POTION_OF_AWESOME_WINGS = "wingpotmax"

all_items_list = [
    HEALTH_POT, #50
    CLAW_SHARPENING, #100
    GASOLINE, #100
    COPPER_PLATING, #100
    BOOK_OF_TRICKS, #100
    POTION_OF_STRONGER_WINGS, #100
    CLAW_HONING, #300
    ROCKET_FUEL, #300
    IRON_PLATING, #300
    BOOK_OF_MEGATRICKS, #300
    POTION_OF_AWESOME_WINGS #300
    ]